"""create table toys

Revision ID: 522b24b9319c
Revises: 5925ba826a22
Create Date: 2020-02-15 14:58:30.025489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '522b24b9319c'
down_revision = '5925ba826a22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('toys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.Text(), nullable=True),
    sa.Column('puppy_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['puppy_id'], ['puppies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('toys')
    # ### end Alembic commands ###
